//
//  CarouselItem.swift
//  IGMetadata
//
//  Created by David Sherlock on 2026.
//

import Foundation

/// A single item in an Instagram carousel/sidecar post.
///
/// Carousel posts contain multiple media items, each of which can be
/// either a photo or a video.
public struct CarouselItem: Sendable {
    
    /// Whether this carousel item is a video.
    public let isVideo: Bool
    
    /// The display URL for this item (photo URL or video thumbnail).
    public let displayUrl: String
    
    /// Video URL, if this item is a video.
    public let videoUrl: String?
    
    /// Video duration in seconds, if this item is a video.
    public let videoDuration: Double?
    
    /// Item width in pixels.
    public let width: Int
    
    /// Item height in pixels.
    public let height: Int
    
    /// The accessibility caption generated by Instagram's AI.
    public let accessibilityCaption: String?
    
}
