//
//  PhotoInfo.swift
//  IGMetadata
//
//  Created by David Sherlock on 2026.
//

import Foundation

/// A photo from an Instagram post.
public struct PhotoInfo: Sendable {
    
    /// The direct image URL.
    public let url: String
    
    /// Image width in pixels.
    public let width: Int
    
    /// Image height in pixels.
    public let height: Int
    
    /// The accessibility caption generated by Instagram's AI.
    public let accessibilityCaption: String?
    
}
